domain {
  frankai.online {
    selector = "mail";
    path = "/var/lib/rspamd/dkim/frankai.online.mail.key";
  }
}
allow_envfrom_empty = false;
allow_hdrfrom_mismatch = false;
allow_hdrfrom_multiple = false;
allow_username_mismatch = false;
sign_local = true;
sign_authenticated = true;
use_domain = "header";
use_esld = false;
try_fallback = false;
