import { NextResponse } from 'next/server'
import { randomBytes, randomUUID } from 'node:crypto'
import { csrfOk, requireRecentAdmin as requireAdmin } from '@/lib/auth/http'
import { audit, hashToken, normaliseEmail } from '@/lib/auth/store'
import { authDb, withAuthTransaction } from '@/lib/auth/postgres'
import { queueEmail } from '@/lib/auth/email'
import { allowRequest } from '@/lib/auth/rate-limit'
export const runtime = 'nodejs'
export async function GET(request: Request) { const auth = await requireAdmin(request); if (auth.response) return auth.response; const url = new URL(request.url); const limit = Math.min(100, Math.max(1, Number(url.searchParams.get('limit') || 25))); const offset = Math.max(0, Number(url.searchParams.get('offset') || 0)); const result = await authDb().query('SELECT id,email_normalized,role,expires_at,used_at,revoked_at,created_at FROM invitations ORDER BY created_at DESC LIMIT $1 OFFSET $2', [limit, offset]); return NextResponse.json({ invitations: result.rows }) }
export async function POST(request: Request) { const auth = await requireAdmin(request); if (auth.response) return auth.response; if (!csrfOk(request)) return NextResponse.json({ error: 'CSRF validation failed' }, { status: 403 }); const limit = await allowRequest(request, 'admin_sensitive_action', auth.user!.id); if (!limit.allowed) return NextResponse.json({ error: 'Too many requests.' }, { status: 429, headers: { 'Retry-After': String(limit.retryAfter) } }); const body = await request.json().catch(() => ({})); const email = typeof body.email === 'string' ? normaliseEmail(body.email) : ''; const role = body.role === 'ADMIN' ? 'ADMIN' : 'USER'; if (!/^\S+@\S+\.\S+$/.test(email)) return NextResponse.json({ error: 'Invalid invitation.' }, { status: 400 }); if (role === 'ADMIN' && body.confirmAdminRole !== true) return NextResponse.json({ error: 'Administrator role confirmation is required.' }, { status: 400 }); const token = randomBytes(32).toString('base64url'); const id = randomUUID(); const expires = new Date(Date.now() + 7 * 86400000); await withAuthTransaction(async client => { const existing = await client.query("SELECT id FROM invitations WHERE email_normalized=$1 AND used_at IS NULL AND revoked_at IS NULL AND expires_at>now() FOR UPDATE", [email]); if (existing.rowCount) throw new Error('active_invitation_exists'); await client.query('INSERT INTO invitations (id,email_normalized,token_hash,role,expires_at,created_by) VALUES ($1,$2,$3,$4,$5,$6)', [id,email,hashToken(token),role,expires,auth.user!.id]); await client.query('INSERT INTO audit_events (id,actor_user_id,action,result,target_type,target_id,metadata_json) VALUES ($1,$2,$3,$4,$5,$6,$7)', [randomUUID(),auth.user!.id,role === 'ADMIN' ? 'admin_invitation_created' : 'invitation_created','success','invitation',id,JSON.stringify({ role })]) }); await queueEmail(email, 'invitation', { invitationId: id, role, token, expiresAt: expires.toISOString() }); await audit('invitation_created', 'success', { invitationId: id, role }, auth.user!.id); return NextResponse.json({ id, email, role, expiresAt: expires.toISOString(), invitationToken: token }, { status: 201 }) }
