'use client'
import Image from 'next/image'
import { useEffect, useState } from 'react'

const csrf = () => document.cookie.match(/(?:^|;\s*)frankai_csrf=([^;]+)/)?.[1] || ''

export default function AdminMfaPage(){
  const [enrolled,setEnrolled]=useState(false); const [uri,setUri]=useState(''); const [qrCode,setQrCode]=useState(''); const [code,setCode]=useState(''); const [codes,setCodes]=useState<string[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  useEffect(()=>{ void fetch('/api/auth/me',{credentials:'include'}).then(r=>r.json()).then(data=>setEnrolled(Boolean(data.user?.mfaEnrolledAt))).catch(()=>setError('Unable to load MFA status.')) },[])
  async function post(path:string, body?:Record<string,string>){const request=()=>fetch(path,{method:'POST',credentials:'include',headers:{...(body?{'content-type':'application/json'}:{}),'x-csrf-token':csrf()},...(body?{body:JSON.stringify(body)}:{})});let r=await request();if(r.status===401){const refresh=await fetch('/api/auth/refresh',{method:'POST',credentials:'include',headers:{'x-csrf-token':csrf()}});if(refresh.ok)r=await request()}return r}
  async function setup(){setBusy(true);setError('');const r=await post('/api/admin/mfa/setup');const data=await r.json();if(r.ok){setUri(data.uri);setQrCode(data.qrCode||'')}else setError(r.status===401?'Your session expired. Sign in again.':data.error||'MFA setup unavailable');setBusy(false)}
  async function submit(path:string){setBusy(true);setError('');const r=await post(path,{code});const data=await r.json();if(r.ok){if(path.endsWith('/confirm'))setCodes(data.recoveryCodes||[]);else location.href='/admin'}else setError(r.status===401?'Your session expired or the MFA session is no longer valid.':data.error||'Invalid MFA code.');setBusy(false)}
  return <main className="page-shell"><section className="content-section"><p className="eyebrow">Administrator security</p>{enrolled?<><h1>Verify MFA.</h1><p>Enter the six-digit code from your authenticator app to continue.</p><form onSubmit={e=>{e.preventDefault();void submit('/api/admin/mfa/challenge')}} className="contact-form"><label>Authenticator code<input autoFocus inputMode="numeric" pattern="[0-9]{6}" required value={code} onChange={e=>setCode(e.target.value)}/></label><button disabled={busy}>Verify code</button></form><form onSubmit={e=>{e.preventDefault();void submit('/api/admin/mfa/recovery')}} className="contact-form"><label>Recovery code<input inputMode="text" value={code} onChange={e=>setCode(e.target.value)}/></label><button disabled={busy}>Use recovery code</button></form></>:<><h1>Set up MFA.</h1><p>Scan this QR code with your authenticator app. Recovery codes are shown once and must be stored offline.</p><button disabled={busy} onClick={setup}>Generate setup secret</button>{qrCode&&<div className="mfa-qr"><Image src={qrCode} alt="MFA setup QR code" width={280} height={280} unoptimized/><p>If scanning is unavailable, use the manual setup URI below.</p></div>}{uri&&<p><code>{uri}</code></p>}<form onSubmit={e=>{e.preventDefault();void submit('/api/admin/mfa/confirm')}} className="contact-form"><label>Authenticator code<input inputMode="numeric" pattern="[0-9]{6}" required value={code} onChange={e=>setCode(e.target.value)}/></label><button disabled={busy}>Confirm MFA</button></form></>}{codes.length>0&&<><pre>{codes.join('\n')}</pre><button onClick={()=>{location.href='/admin'}}>I stored my recovery codes</button></>}{error&&<p role="alert">{error}</p>}</section></main>}
