import type { Metadata } from 'next'
import Link from 'next/link'
import { AIConsultingTeaser } from '@/components/AIConsultingTeaser'
import { PortfolioCard } from '@/components/PortfolioCard'
import { SectionIntro } from '@/components/SectionIntro'
import { portfolio } from '@/lib/portfolio'

export const metadata: Metadata = { title: 'Solutions', description: 'Applied AI engineering, governed automation and workflow systems from FrankAI.' }

export default function SolutionsPage() { return <section className="page-section"><div className="container"><SectionIntro eyebrow="Solutions" title="AI that belongs inside real operations." text="FrankAI solutions focus on structured work: intake, coordination, service delivery, evidence, integration and controlled automation." /><AIConsultingTeaser /><div className="feature-grid"><article className="feature-card"><h2>Workflow design</h2><p>Map repetitive operational work into systems that can be assisted, reviewed and governed.</p></article><article className="feature-card"><h2>Systems integration</h2><p>Connect applications, data and agent workflows while making boundaries and failure modes visible.</p></article><article className="feature-card"><h2>Sovereign operations</h2><p>Explore local, private and recoverable architectures where infrastructure independence matters.</p></article><article className="feature-card"><h2>Evidence-centric systems</h2><p>Build records, provenance and auditability into the workflow rather than adding them after the fact.</p></article></div><section className="proof-section"><SectionIntro eyebrow="Selected platforms" title="Capability with a clear boundary." text="Status is based on current implementation maturity. Labs and private systems are not presented as finished public products." /><div className="card-grid three">{portfolio.filter((item) => item.category === 'Platform').map((item) => <PortfolioCard item={item} key={item.id} />)}</div></section><div className="inline-cta"><p>Have a process that is slow, fragmented or hard to control?</p><Link className="text-link" href="/contact">Discuss a workflow <span aria-hidden="true">-&gt;</span></Link></div></div></section> }
