import { NextResponse } from 'next/server'
import { csrfOk, requireUser, setAccessCookie } from '@/lib/auth/http'
import { checkTotp, consumeRecoveryCode } from '@/lib/auth/mfa'
import { audit } from '@/lib/auth/store'
import { issueAccessToken, verifyAccessToken } from '@/lib/auth/jwt'
import { authDb } from '@/lib/auth/postgres'
import { allowRequest } from '@/lib/auth/rate-limit'
export const runtime = 'nodejs'
export async function POST(request: Request) { const auth = await requireUser(request); if (auth.response) return auth.response; if (auth.user!.role !== 'ADMIN') return NextResponse.json({ error: 'Forbidden' }, { status: 403 }); if (!csrfOk(request)) return NextResponse.json({ error: 'CSRF validation failed' }, { status: 403 }); const limit = await allowRequest(request, 'mfa_challenge', auth.user!.id); if (!limit.allowed) return NextResponse.json({ error: 'Too many MFA attempts.' }, { status: 429, headers: { 'Retry-After': String(limit.retryAfter) } }); const body = await request.json().catch(() => ({})); const code = typeof body.code === 'string' ? body.code : ''; const totp = await checkTotp(auth.user!.id, code); const recovery = !totp && await consumeRecoveryCode(auth.user!.id, code); if (!totp && !recovery) { await audit('admin_reauth', 'failure', {}, auth.user!.id); return NextResponse.json({ error: 'MFA challenge failed.' }, { status: 401 }) } const token = issueAccessToken(auth.user!, true); const claims = verifyAccessToken(token); if (!claims) return NextResponse.json({ error: 'Unable to establish assurance.' }, { status: 503 }); const maxAge = Number(process.env.ADMIN_REAUTH_MAX_AGE_SECONDS || 600); const method = totp ? 'totp' : 'recovery_code'; await authDb().query('INSERT INTO admin_reauth_assurances (jti,user_id,method,expires_at) VALUES ($1,$2,$3,now()+($4 || \' seconds\')::interval)', [claims.jti,auth.user!.id,method,maxAge]); const response = NextResponse.json({ ok: true, expiresIn: maxAge }); setAccessCookie(response, token); await audit('admin_reauth', 'success', { method }, auth.user!.id); return response }
