import { NextResponse } from 'next/server'
import { randomBytes } from 'node:crypto'
import { verifyAccessToken } from './jwt'
import { users, sessions, hashToken, audit, type User } from './store'
import { authConfig, safeEqual } from './config'
import { authDb } from './postgres'

export const ACCESS_COOKIE = '__Host-frankai_access'
export const REFRESH_COOKIE = '__Host-frankai_refresh'
export const CSRF_COOKIE = 'frankai_csrf'
export function cookieOptions(maxAge: number, httpOnly = true) { const c = authConfig(); return { httpOnly, secure: c.cookieSecure, sameSite: c.sameSite, path: '/', maxAge } as const }
export function setAuthCookies(response: NextResponse, access: string, refresh: string) { const c = authConfig(); response.cookies.set(ACCESS_COOKIE, access, cookieOptions(c.accessTtlSeconds)); response.cookies.set(REFRESH_COOKIE, refresh, cookieOptions(c.refreshTtlSeconds)); response.cookies.set(CSRF_COOKIE, randomBytes(24).toString('base64url'), cookieOptions(c.refreshTtlSeconds, false)) }
export function setAccessCookie(response: NextResponse, access: string) { const c = authConfig(); response.cookies.set(ACCESS_COOKIE, access, cookieOptions(c.accessTtlSeconds)) }
export function clearAuthCookies(response: NextResponse) { response.cookies.set(ACCESS_COOKIE, '', cookieOptions(0)); response.cookies.set(REFRESH_COOKIE, '', cookieOptions(0)); response.cookies.set(CSRF_COOKIE, '', cookieOptions(0, false)) }
export function csrfOk(request: Request) { const method = request.method.toUpperCase(); if (['GET', 'HEAD', 'OPTIONS'].includes(method)) return true; const cookie = request.headers.get('cookie')?.match(/(?:^|;\s*)frankai_csrf=([^;]+)/)?.[1]; const header = request.headers.get('x-csrf-token'); const origin = request.headers.get('origin'); const allowedOrigin = new URL(authConfig().issuer).origin; const originValid = !origin || origin === allowedOrigin; return Boolean(cookie && header && safeEqual(decodeURIComponent(cookie), header) && originValid) }
export async function authenticatedUser(request: Request): Promise<User | null> { const cookie = request.headers.get('cookie')?.match(/(?:^|;\s*)__Host-frankai_access=([^;]+)/)?.[1]; if (!cookie) return null; const claims = verifyAccessToken(decodeURIComponent(cookie)); if (!claims) return null; const user = (await users()).find(item => item.id === claims.sub); return user && user.status === 'ACTIVE' && user.role === claims.role && user.securityVersion === claims.securityVersion && user.roleVersion === claims.roleVersion ? user : null }
export async function requireUser(request: Request) { const user = await authenticatedUser(request); if (!user) return { user: null, response: NextResponse.json({ error: 'Unauthorised' }, { status: 401 }) }; return { user, response: null }
}
export async function requireAdmin(request: Request) { const result = await requireUser(request); if (result.response) return result; if (result.user!.role !== 'ADMIN') return { user: null, response: NextResponse.json({ error: 'Forbidden' }, { status: 403 }) }; const claims = accessClaims(request); if (result.user!.mfaRequired && !claims?.mfa) return { user: null, response: NextResponse.json({ error: 'Administrator MFA is required' }, { status: 403 }) }; return result }
export async function requireRecentAdmin(request: Request) { const result = await requireAdmin(request); if (result.response) return result; const claims = accessClaims(request); if (!claims) return { user: null, response: NextResponse.json({ error: 'Recent MFA reauthentication required', code: 'ADMIN_REAUTH_REQUIRED' }, { status: 401 }) }; const assurance = await authDb().query('SELECT 1 FROM admin_reauth_assurances WHERE jti=$1 AND user_id=$2 AND expires_at>now()', [claims.jti, result.user!.id]); if (!assurance.rowCount) return { user: null, response: NextResponse.json({ error: 'Recent MFA reauthentication required', code: 'ADMIN_REAUTH_REQUIRED' }, { status: 401 }) }; return result }
export function accessClaims(request: Request) { const cookie = request.headers.get('cookie')?.match(/(?:^|;\s*)__Host-frankai_access=([^;]+)/)?.[1]; return cookie ? verifyAccessToken(decodeURIComponent(cookie)) : null }
export async function revokeRefreshToken(raw: string | undefined, reason: string) { if (!raw) return; const list = await sessions(); const session = list.find(item => item.tokenHash === hashToken(raw)); if (session && !session.revokedAt) { session.revokedAt = Date.now(); await (await import('./store')).saveSessions(list); await audit(reason, 'success', { sessionId: session.id }, session.userId) } }
