import { createCipheriv, createDecipheriv, createHmac, randomBytes, randomUUID, createHash } from 'node:crypto'
import pg from 'pg'

const { Pool } = pg
let pool: pg.Pool | null = null
function db() { if (!process.env.DATABASE_URL || process.env.AUTH_DATABASE_ENABLED !== 'true') throw new Error('MFA database is not configured'); if (!pool) pool = new Pool({ connectionString: process.env.DATABASE_URL, max: 3 }); return pool }
function key() { const value = process.env.MFA_ENCRYPTION_KEY || ''; if (!/^[0-9a-f]{64}$/i.test(value)) throw new Error('MFA_ENCRYPTION_KEY is not configured'); return Buffer.from(value, 'hex') }
function b32(value: Buffer) { return value.toString('base64').replace(/=/g, '').replace(/\+/g, '').replace(/\//g, '').toUpperCase().slice(0, 32) }
function b32decode(value: string) { const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'; let bits = ''; for (const char of value.toUpperCase().replace(/=+$/, '')) { const n = alphabet.indexOf(char); if (n < 0) throw new Error('Invalid secret'); bits += n.toString(2).padStart(5, '0') } const bytes: number[] = []; for (let i = 0; i + 8 <= bits.length; i += 8) bytes.push(parseInt(bits.slice(i, i + 8), 2)); return Buffer.from(bytes) }
function encrypt(secret: string) { const iv = randomBytes(12); const cipher = createCipheriv('aes-256-gcm', key(), iv); const value = Buffer.concat([cipher.update(secret, 'utf8'), cipher.final()]); return `${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${value.toString('base64url')}` }
function decrypt(value: string) { const [iv, tag, ciphertext] = value.split('.'); const decipher = createDecipheriv('aes-256-gcm', key(), Buffer.from(iv, 'base64url')); decipher.setAuthTag(Buffer.from(tag, 'base64url')); return Buffer.concat([decipher.update(Buffer.from(ciphertext, 'base64url')), decipher.final()]).toString('utf8') }
export function newTotpSecret() { return b32(randomBytes(20)) }
export function totpUri(email: string, secret: string) { return `otpauth://totp/FrankAI:${encodeURIComponent(email)}?secret=${secret}&issuer=FrankAI&algorithm=SHA1&digits=6&period=30` }
export function verifyTotp(secret: string, code: string) { if (!/^\d{6}$/.test(code)) return false; const counter = Math.floor(Date.now() / 30000); for (let offset = -1; offset <= 1; offset++) { const data = Buffer.alloc(8); data.writeBigUInt64BE(BigInt(counter + offset)); const digest = createHmac('sha1', b32decode(secret)).update(data).digest(); const index = digest[digest.length - 1] & 15; const value = ((digest[index] & 0x7f) << 24) | (digest[index + 1] << 16) | (digest[index + 2] << 8) | digest[index + 3]; if (String(value % 1000000).padStart(6, '0') === code) return true } return false }
export async function beginSetup(userId: string) { const secret = newTotpSecret(); await db().query(`INSERT INTO admin_mfa_secrets (user_id, encrypted_secret) VALUES ($1,$2) ON CONFLICT (user_id) DO UPDATE SET encrypted_secret=$2,confirmed_at=NULL,updated_at=now()`, [userId, encrypt(secret)]); return secret }
export async function confirmSetup(userId: string, code: string) { const result = await db().query('SELECT encrypted_secret FROM admin_mfa_secrets WHERE user_id=$1 AND confirmed_at IS NULL', [userId]); if (!result.rowCount) return null; const secret = decrypt(result.rows[0].encrypted_secret); if (!verifyTotp(secret, code)) return null; const client = await db().connect(); const codes = Array.from({ length: 10 }, () => randomBytes(5).toString('hex')); try { await client.query('BEGIN'); await client.query('UPDATE admin_mfa_secrets SET confirmed_at=now(),updated_at=now() WHERE user_id=$1', [userId]); await client.query('DELETE FROM mfa_recovery_codes WHERE user_id=$1', [userId]); for (const codeValue of codes) await client.query('INSERT INTO mfa_recovery_codes (id,user_id,code_hash) VALUES ($1,$2,$3)', [randomUUID(), userId, createHash('sha256').update(codeValue).digest('hex')]); await client.query("UPDATE users SET mfa_required=true,mfa_enrolled_at=now(),updated_at=now() WHERE id=$1", [userId]); await client.query('COMMIT'); return codes } catch (error) { await client.query('ROLLBACK'); throw error } finally { client.release() } }
export async function checkTotp(userId: string, code: string) { const result = await db().query('SELECT encrypted_secret,confirmed_at FROM admin_mfa_secrets WHERE user_id=$1', [userId]); if (!result.rowCount || !result.rows[0].confirmed_at) return false; return verifyTotp(decrypt(result.rows[0].encrypted_secret), code) }
export async function consumeRecoveryCode(userId: string, code: string) { const hash = createHash('sha256').update(code.trim().toLowerCase()).digest('hex'); const result = await db().query('UPDATE mfa_recovery_codes SET used_at=now() WHERE user_id=$1 AND code_hash=$2 AND used_at IS NULL RETURNING id', [userId, hash]); return Boolean(result.rowCount) }
