import { randomBytes, randomUUID, scrypt as scryptCallback, createHash } from 'node:crypto'
import { mkdir, readFile, rename, appendFile, chmod } from 'node:fs/promises'
import { promisify } from 'node:util'
import { authConfig } from './config'
import pg from 'pg'
import { redactAuditMetadata } from './redaction'
import { auditDefinition } from './audit-registry'

const scrypt = promisify(scryptCallback)
export type Role = 'USER' | 'ADMIN'
export type Status = 'ACTIVE' | 'DISABLED' | 'LOCKED' | 'PENDING_VERIFICATION'
export type User = { id: string; email: string; displayName: string; passwordHash: string; passwordHashVersion: number; role: Role; roleVersion: number; securityVersion: number; status: Status; emailVerifiedAt: string | null; failedLoginCount: number; lockedUntil: number | null; lastLoginAt: string | null; passwordChangedAt: string; mfaRequired: boolean; mfaEnrolledAt: string | null; createdAt: string; updatedAt: string }
export type Session = { id: string; userId: string; tokenHash: string; tokenFamily: string; expiresAt: number; revokedAt: number | null; replacedBySessionId: string | null; createdAt: string; lastUsedAt: number | null }

async function ensureDir() { await mkdir(authConfig().dataDir, { recursive: true, mode: 0o700 }) }
const databaseEnabled = () => Boolean(process.env.DATABASE_URL && process.env.AUTH_DATABASE_ENABLED === 'true')
let pool: pg.Pool | null = null
function database() { if (!pool) pool = new pg.Pool({ connectionString: process.env.DATABASE_URL, max: 5, ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: true } : undefined }); return pool }
async function readJson<T>(name: string, fallback: T): Promise<T> { await ensureDir(); try { return JSON.parse(await readFile(`${authConfig().dataDir}/${name}`, 'utf8')) as T } catch (e) { if ((e as NodeJS.ErrnoException).code === 'ENOENT') return fallback; throw e } }
async function writeJson(name: string, value: unknown) { await ensureDir(); const path = `${authConfig().dataDir}/${name}`; const tmp = `${path}.${process.pid}.${randomUUID()}.tmp`; await (await import('node:fs/promises')).writeFile(tmp, JSON.stringify(value, null, 2), { mode: 0o600 }); await rename(tmp, path) }
export function normaliseEmail(email: string) { return email.trim().toLowerCase() }
const derive = (password: string, salt: string) => (scrypt as unknown as (password: string, salt: string, keylen: number, options: object) => Promise<Buffer>)(password, salt, 64, { N: 16384, r: 8, p: 1, maxmem: 64 * 1024 * 1024 })
export async function hashPassword(password: string) { const salt = randomBytes(16).toString('hex'); const derived = await derive(password, salt); return `scrypt$${salt}$${derived.toString('hex')}` }
export async function verifyPassword(password: string, encoded: string) { const [, salt, expected] = encoded.split('$'); if (!salt || !expected) return false; const derived = await derive(password, salt); return derived.length === Buffer.from(expected, 'hex').length && derived.equals(Buffer.from(expected, 'hex')) }
export function hashToken(token: string) { return createHash('sha256').update(token).digest('hex') }
export function fromUserRow(row: Record<string, unknown>): User { return { id: String(row.id), email: String(row.email), displayName: String(row.display_name), passwordHash: String(row.password_hash), passwordHashVersion: Number(row.password_hash_version || 1), role: row.role as Role, roleVersion: Number(row.role_version || 1), securityVersion: Number(row.security_version || 1), status: row.status as Status, emailVerifiedAt: row.email_verified_at ? new Date(String(row.email_verified_at)).toISOString() : null, failedLoginCount: Number(row.failed_login_count || 0), lockedUntil: row.locked_until ? new Date(String(row.locked_until)).getTime() : null, lastLoginAt: row.last_login_at ? new Date(String(row.last_login_at)).toISOString() : null, passwordChangedAt: new Date(String(row.password_changed_at)).toISOString(), mfaRequired: Boolean(row.mfa_required), mfaEnrolledAt: row.mfa_enrolled_at ? new Date(String(row.mfa_enrolled_at)).toISOString() : null, createdAt: new Date(String(row.created_at)).toISOString(), updatedAt: new Date(String(row.updated_at)).toISOString() } }
function fromSessionRow(row: Record<string, unknown>): Session { return { id: String(row.id), userId: String(row.user_id), tokenHash: String(row.token_hash), tokenFamily: String(row.token_family), expiresAt: new Date(String(row.expires_at)).getTime(), revokedAt: row.revoked_at ? new Date(String(row.revoked_at)).getTime() : null, replacedBySessionId: row.replaced_by_session_id ? String(row.replaced_by_session_id) : null, createdAt: new Date(String(row.created_at)).toISOString(), lastUsedAt: row.last_used_at ? new Date(String(row.last_used_at)).getTime() : null } }
function normaliseFileUser(user: Partial<User> & { id: string; email: string; displayName: string; passwordHash: string }): User { const now = new Date().toISOString(); return { id: user.id, email: user.email, displayName: user.displayName, passwordHash: user.passwordHash, passwordHashVersion: user.passwordHashVersion || 1, role: user.role || 'USER', roleVersion: user.roleVersion || 1, securityVersion: user.securityVersion || 1, status: user.status || 'ACTIVE', emailVerifiedAt: user.emailVerifiedAt || null, failedLoginCount: user.failedLoginCount || 0, lockedUntil: user.lockedUntil || null, lastLoginAt: user.lastLoginAt || null, passwordChangedAt: user.passwordChangedAt || now, mfaRequired: user.mfaRequired || false, mfaEnrolledAt: user.mfaEnrolledAt || null, createdAt: user.createdAt || now, updatedAt: user.updatedAt || now } }
export async function users() { if (databaseEnabled()) { const result = await database().query('SELECT * FROM users ORDER BY created_at ASC'); return result.rows.map(fromUserRow) } return (await readJson<Array<Partial<User> & { id: string; email: string; displayName: string; passwordHash: string }>>('users.json', [])).map(normaliseFileUser) }
export async function saveUsers(value: User[]) { if (databaseEnabled()) { const client = await database().connect(); try { await client.query('BEGIN'); for (const user of value) await client.query(`INSERT INTO users (id,email,email_normalized,display_name,password_hash,password_hash_version,role,role_version,security_version,status,email_verified_at,failed_login_count,locked_until,last_login_at,password_changed_at,mfa_required,mfa_enrolled_at,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19) ON CONFLICT (id) DO UPDATE SET email=$2,email_normalized=$3,display_name=$4,password_hash=$5,password_hash_version=$6,role=$7,role_version=$8,security_version=$9,status=$10,email_verified_at=$11,failed_login_count=$12,locked_until=$13,last_login_at=$14,password_changed_at=$15,mfa_required=$16,mfa_enrolled_at=$17,updated_at=$19`, [user.id,user.email,user.email,user.displayName,user.passwordHash,user.passwordHashVersion,user.role,user.roleVersion,user.securityVersion,user.status,user.emailVerifiedAt,user.failedLoginCount,user.lockedUntil ? new Date(user.lockedUntil) : null,user.lastLoginAt,user.passwordChangedAt,user.mfaRequired,user.mfaEnrolledAt,user.createdAt,user.updatedAt]); await client.query('COMMIT') } catch (error) { await client.query('ROLLBACK'); throw error } finally { client.release() } } else return writeJson('users.json', value) }
export async function sessions() { if (databaseEnabled()) { const result = await database().query('SELECT * FROM refresh_sessions'); return result.rows.map(fromSessionRow) } return readJson<Session[]>('sessions.json', []) }
export async function saveSessions(value: Session[]) { if (databaseEnabled()) { const client = await database().connect(); try { await client.query('BEGIN'); for (const session of value) await client.query(`INSERT INTO refresh_sessions (id,user_id,token_hash,token_family,replaced_by_session_id,expires_at,revoked_at,created_at,last_used_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT (id) DO UPDATE SET token_hash=$3,token_family=$4,replaced_by_session_id=$5,expires_at=$6,revoked_at=$7,last_used_at=$9`, [session.id,session.userId,session.tokenHash,session.tokenFamily,session.replacedBySessionId,new Date(session.expiresAt),session.revokedAt ? new Date(session.revokedAt) : null,session.createdAt,session.lastUsedAt ? new Date(session.lastUsedAt) : null]); await client.query('COMMIT') } catch (error) { await client.query('ROLLBACK'); throw error } finally { client.release() } } else return writeJson('sessions.json', value) }
export async function createUser(email: string, displayName: string, password: string, role: Role = 'USER') { const list = await users(); const now = new Date().toISOString(); const user: User = { id: randomUUID(), email: normaliseEmail(email), displayName: displayName.trim().slice(0, 120), passwordHash: await hashPassword(password), passwordHashVersion: 1, role, roleVersion: 1, securityVersion: 1, status: 'ACTIVE', emailVerifiedAt: null, failedLoginCount: 0, lockedUntil: null, lastLoginAt: null, passwordChangedAt: now, mfaRequired: role === 'ADMIN', mfaEnrolledAt: null, createdAt: now, updatedAt: now }; list.push(user); await saveUsers(list); return user }
export async function audit(action: string, result: string, metadata: Record<string, unknown> = {}, actorUserId: string | null = null) {
  if (!auditDefinition(action)) throw new Error(`Unregistered audit action: ${action}`)
  const requestId = typeof metadata.requestId === 'string' ? metadata.requestId : randomUUID()
  const safeMetadata = redactAuditMetadata({ ...metadata, requestId })
  if (databaseEnabled()) {
    await database().query('INSERT INTO audit_events (id,actor_user_id,actor_role,action,result,request_id,metadata_json) VALUES ($1,$2,$3,$4,$5,$6,$7)', [randomUUID(), actorUserId, null, action, result, requestId, JSON.stringify(safeMetadata)])
    return
  }
  await ensureDir()
  const file = `${authConfig().dataDir}/audit.jsonl`
  await appendFile(file, JSON.stringify({ id: randomUUID(), timestamp: new Date().toISOString(), actorUserId, action, result, requestId, metadata: safeMetadata }) + '\n')
  await chmod(file, 0o600).catch(() => undefined)
}
export function publicUser(user: User): Omit<User, 'passwordHash'> { const { passwordHash, ...safe } = user; void passwordHash; return safe }
